version: 2.1

executors:
  gig_client:
    docker:
      - image: gigantum/circleci-client:22729ee812-2020-07-14

orbs:
    codecov: codecov/codecov@1.1.0


jobs:
  mypy-gtmcore:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run mypy type checker for gtmcore
          command: |
            python3 -m mypy packages/gtmcore --ignore-missing-imports --strict-optional

  mypy-gtmapi:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run mypy type checker for gtmapi
          command: |
            python3 -m mypy packages/gtmapi --ignore-missing-imports --strict-optional

  test-confhttpproxy:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Test proxy lib
          command: |
            cd ~/repo/packages/confhttpproxy
            echo "import docker; c = docker.from_env()" > runtests.py
            echo "c.images.build(path='.', tag='httpconf')" >> runtests.py
            echo "print(c.containers.run('httpconf', 'pytest /app').decode())" >> runtests.py
            python3 runtests.py
            cd ~/repo

  test-gtmcore:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set authentication credentials
          command: bash /home/circleci/repo/.circleci/write_auth.sh
      - run:
          name: Run Core unit and coverage tests
          command: |
            export PYTHONPATH=$PYTHONPATH:/home/circleci/repo/packages/gtmcore
            export SKIP_ENV_TESTS=1
            export SKIP_BG_TESTS=1
            redis-server > /dev/null 2> /dev/null &
            rqscheduler --interval=2 --db 13 2> /dev/null &
            python3 /home/circleci/repo/packages/gtmcore/gtmcore/dispatcher/worker.py &
            pytest --cov=gtmcore packages/gtmcore/gtmcore/
      - codecov/upload:
          flags: core

  test-gtmapi:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set authentication credentials
          command: bash /home/circleci/repo/.circleci/write_auth.sh
      - run:
          name: Run API unit, integration and coverage tests
          command: |
            export PYTHONPATH=$PYTHONPATH:/home/circleci/repo/packages/gtmcore
            export SKIP_ENV_TESTS=1
            export SKIP_BG_TESTS=1
            cd /home/circleci/repo
            redis-server > /dev/null 2> /dev/null &
            rqscheduler --interval=2 2> /dev/null &
            python3 /home/circleci/repo/packages/gtmcore/gtmcore/dispatcher/worker.py &
            pytest --cov=lmsrvlabbook --cov=lmsrvcore packages/gtmapi/lmsrvlabbook
            pytest --cov=lmsrvlabbook --cov=lmsrvcore --cov-append packages/gtmapi/lmsrvcore
      - codecov/upload:
          flags: api

  test-gtmcore-environment:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set authentication credentials
          command: bash /home/circleci/repo/.circleci/write_auth.sh
      - run:
          name: Run gtmcore environment tests
          command: |
            export PYTHONPATH=$PYTHONPATH:/home/circleci/repo/packages/gtmcore
            cd /home/circleci/repo
            redis-server > /dev/null 2> /dev/null &
            rqscheduler --interval=2 2> /dev/null &
            python3 /home/circleci/repo/packages/gtmcore/gtmcore/dispatcher/worker.py &
            pytest --cov=gtmcore packages/gtmcore/gtmcore/environment/tests
      - codecov/upload:
          flags: core

  test-background-jobs:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set authentication credentials
          command: bash /home/circleci/repo/.circleci/write_auth.sh
      - run:
          name: Run Dispatcher and background job tests
          command: |
            export PYTHONPATH=$PYTHONPATH:/home/circleci/repo/packages/gtmcore
            cd /home/circleci/repo
            pytest --cov=gtmcore packages/gtmcore/gtmcore/dispatcher/tests/test_dispatcher.py::test_redis_not_running
            redis-server > /dev/null 2> /dev/null &
            rqscheduler --interval=2 --db 13 2> /dev/null &
            python3 /home/circleci/repo/packages/gtmcore/gtmcore/dispatcher/worker.py &
            pytest --cov=gtmcore --cov-append packages/gtmcore/gtmcore/dispatcher/tests -k "not test_redis_not_running"
      - codecov/upload:
          flags: core

  test-ui-components:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build frontend production code
          command: |
            cd /home/circleci/repo/ui
            yarn install
            yarn relay
            unset CI && yarn build
      - run:
          name: Run jest tests
          no_output_timeout: 15m
          command: |
            cd /home/circleci/repo/ui
            TZ='Europe/London' jest --maxWorkers=2 src -u

  fossa:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build frontend production code
          command: |
            cd /home/circleci/repo/ui
            npm install
            npm install relay
      - run:
          name: Run Fossa
          command: fossa
          working_directory: /home/circleci/repo/
      - run:
          name: Enforce Fossa checks
          command: fossa test --timeout 1200 --no-ansi
          working_directory: /home/circleci/repo/

  changelog-schema-check:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies for changelog verification
          command: |
            cd changelog
            pip3 install -r ./requirements.txt
      - run:
          name: Validate all changelog files for schema errors
          command: |
            cd changelog
            python3 ./validate.py schema

  changelog-pr-check:
    executor: gig_client
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies for changelog verification
          command: |
            cd changelog
            pip3 install -r ./requirements.txt
      - run:
          name: Verify this PR contains changelog information
          command: |
            cd changelog
            python3 ./validate.py pr


workflows:
  version: 2
  run_tests:
    jobs:
      - changelog-schema-check
      - changelog-pr-check:
          # Don't run the changelog PR check when merging FROM master or integration
          filters:
            branches:
              ignore:
                - master
                - integration
      - mypy-gtmcore
      - mypy-gtmapi
      - test-gtmcore-environment:
          requires:
            - mypy-gtmcore
            - mypy-gtmapi
      - test-confhttpproxy:
          requires:
            - mypy-gtmcore
            - mypy-gtmapi
      - test-gtmcore:
          requires:
            - mypy-gtmcore
            - mypy-gtmapi
      - test-gtmapi:
          requires:
            - mypy-gtmcore
            - mypy-gtmapi
      - test-ui-components:
          requires:
            - mypy-gtmcore
            - mypy-gtmapi
      - test-background-jobs:
          requires:
            - mypy-gtmcore
            - mypy-gtmapi
      - fossa:
          requires:
            - mypy-gtmcore
            - mypy-gtmapi
