configuration:
  chrome_driver_version: "2.36"
  edge_driver_version: "84.0.522.15"
  window_size: "1440,900"
  test_environment: dev
  browsers: ["chrome", "firefox"]
  incognito: True
  headless: False
  default_server: "gigantum-com"
  api_url: "http://localhost:10000/api/labbook"
